import Head from 'next/head'
import { Stack, Typography, useMediaQuery } from "@mui/material";
import useTranslation from "next-translate/useTranslation";
import Image from 'next/image';
import styled from "@emotion/styled";
import Logo from "@/src/components/Logo";
import { Colors } from "@/styles/Colors";
import Grid2 from "@mui/material/Unstable_Grid2";
import { Feature } from "@/src/types";

export default function Home() {
  const { t } = useTranslation('common');
  const features: Feature[] = t('features', {}, { returnObjects: true })
  const isBreakpoint = useMediaQuery('(min-width: 970px)');

  return (
    <>
      <Head>
        <title>Home | Nextblog</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Stack sx={{ py: 7 }}
             gap={10}
             direction={'row'}
             flexWrap={'wrap'}
             justifyContent={isBreakpoint ? 'flex-start' : 'center'}
      >
        <Stack>
          <Typography sx={{ width: isBreakpoint ? 360 : 'auto' }} variant={'h2'}>{t('title')}</Typography>
          <Logo variant={'h1'}/>
          <Typography component={'span'} color={Colors.grey}>{t('minititle')}</Typography>
        </Stack>
        <StyleImage src={'/images/logo.jpg'} height={450} width={450} alt={'hero'}/>
      </Stack>
      <Typography variant={'h4'} sx={{ textAlign: 'left', mt: 10, fontWeight: 700 }}>{t('subtitle')}</Typography>
      <Grid2 sx={{ mt: 3 }} container spacing={5} columns={{ xs: 6, sm: 12 }}>
        {features?.map(({ title, content }, index) => {
          return <Grid2 key={title + index} xs={6} sm={6} md={4}>
            <Typography sx={{ fontWeight: 700, fontSize: '1.5em' }}>{title}</Typography>
            <Typography variant={'body1'}>{content}</Typography>
          </Grid2>
        })}
      </Grid2>
    </>
  )
}

const StyleImage = styled(Image)`
  border-radius: 10px;
  height: auto;
  width: 100%;
  max-width: 450px;
  @media (min-width: 970px) {
    margin-left: auto;
  }
`
